### ISSUE TITLE
Why not contributed to Laravel-Fakeid?

### ISSUE THREAD

**Issue by Propaganistas** [cybercog/laravel-optimus#8]
Out of curiosity: why creating a second Optimus wrapper package instead of contributing to the [existing one](https://github.com/propaganistas/laravel-fakeid)?

**Comment by a-komarev** [comment]
Hello, @Propaganistas. Because it was private package which was created in 2015 and open sourced in 2017. And already using in our projects.
When I've searched over GitHub by the keywords `laravel optimus` I haven't found your package then created a new one. As you can see your project is listed in Alternatives section in documentation.

**Comment by a-komarev** [comment]
Closing this issue. Feel free to continue conversation here.
